[package]
name = "tpt-med-vv40"
description = "ASME V&V 40 credibility assessment matrices"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]


[lints]
workspace = true
