//! Generates a `(crate name, resolved version)` table from the workspace
//! `Cargo.lock`, for `tpt_med_examples::crate_versions`.
//!
//! `Cargo.lock` is the one place Cargo itself records the *resolved* version
//! of every crate in the workspace, independent of how that version was
//! computed (`version.workspace = true` today, an independent per-crate
//! version tomorrow). Reading it here, instead of hard-coding
//! `env!("CARGO_PKG_VERSION")` for every participating crate, is what keeps
//! `tpt-med-fda`'s `ReproducibilityManifest` correct once crates stop
//! versioning as a single unit.
//!
//! Deliberately dependency-free: `Cargo.lock`'s `[[package]] name = "..." /
//! version = "..."` shape is stable enough to line-scan without pulling in a
//! TOML parser for a build script that only three fields matter to.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("set by cargo");
    let lock_path = Path::new(&manifest_dir).join("../Cargo.lock");
    println!("cargo:rerun-if-changed={}", lock_path.display());

    let lock = fs::read_to_string(&lock_path)
        .unwrap_or_else(|e| panic!("reading {}: {e}", lock_path.display()));

    let mut versions: Vec<(String, String)> = Vec::new();
    let mut pending_name: Option<String> = None;
    for raw_line in lock.lines() {
        let line = raw_line.trim();
        if line == "[[package]]" {
            pending_name = None;
        } else if let Some(name) = line
            .strip_prefix("name = \"")
            .and_then(|s| s.strip_suffix('"'))
        {
            pending_name = Some(name.to_string());
        } else if let Some(version) = line
            .strip_prefix("version = \"")
            .and_then(|s| s.strip_suffix('"'))
        {
            if let Some(name) = pending_name.take() {
                // Only the workspace's own crates: an external dependency
                // happening to start with "tpt-med-" is not a scenario this
                // workspace's naming makes possible, but scoping the prefix
                // keeps the generated table small and on-topic regardless.
                if name.starts_with("tpt-med-") {
                    versions.push((name, version.to_string()));
                }
            }
        }
    }
    versions.sort();
    versions.dedup();

    let mut out = String::from(
        "// Generated by `examples/build.rs` from the workspace `Cargo.lock`.\n\
         // Do not edit by hand; re-run `cargo build` to regenerate.\n\n\
         /// `(crate name, resolved version)` for every `tpt-med-*` workspace\n\
         /// member present in `Cargo.lock` as of the last build.\n\
         pub static CRATE_VERSIONS: &[(&str, &str)] = &[\n",
    );
    for (name, version) in &versions {
        out.push_str(&format!("    ({name:?}, {version:?}),\n"));
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("set by cargo");
    let dest = Path::new(&out_dir).join("crate_versions.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("writing {}: {e}", dest.display()));
}
