#!/usr/bin/env bash
#
# bench-baseline.sh - run the benchmark suite and fail if a stage regressed
# beyond its stored baseline.
#
# Usage:
#   scripts/bench-baseline.sh              # run, compare, fail on regression
#   scripts/bench-baseline.sh --update     # run and rewrite the baseline
#
# The baseline lives in benches/baseline.txt and is a list of
#   <benchmark>/<stage> <nanoseconds>
# lines. That format is intentionally boring: it is greppable, diffable, and
# survives a reformat.
#
# Why percentages and not an absolute budget: these are *shared, noisy* CI
# runners. An absolute millisecond budget produces false failures that train
# people to ignore the job. The default threshold is deliberately generous
# (25 %) and is meant to catch an algorithmic regression - a dropped
# optimisation, an accidental O(n^2), a lost fast path - not a 5 % wobble.
# A real regression in this codebase is usually 2x or more.
#
# Run locally before pushing a change to a hot path.

set -euo pipefail

cd "$(dirname "$0")/.."
BASELINE="benches/baseline.txt"
THRESHOLD_PCT="${TPT_BENCH_THRESHOLD_PCT:-25}"
UPDATE=0
[ "${1:-}" = "--update" ] && UPDATE=1

if ! command -v python3 >/dev/null 2>&1; then
  echo "ERROR: python3 is required (not found on PATH)." >&2
  exit 2
fi
raw="$(mktemp)"
trap 'rm -f "$raw"' EXIT

echo "Running benchmark suite (this builds in release and takes a few minutes) ..."
cargo bench -p tpt-med-benches 2>&1 | tee "$raw"

# The harness-free benches print lines of the form
#   "  parse 24 slices                    1.23ms"
# so parse the label and the human duration back into nanoseconds.
python3 - "$raw" "$THRESHOLD_PCT" "$UPDATE" "$BASELINE" <<'PYEOF'
import re, sys, os

raw, threshold, update, baseline_path = sys.argv[1], float(sys.argv[2]), sys.argv[3] == "1", sys.argv[4]

UNIT = {"ns": 1, "us": 1e3, "ms": 1e6, "s": 1e9}
BENCH = re.compile(r"^(\S+)\s+benchmark\b")
# The benches print a label, then a run of 2+ spaces of column padding, then
# the duration:  "  hex FEM 16x4x4 solve            24.28ms  (sink 0.9811)".
# Requiring the padding run is what keeps prose lines like
# "~246.5 steps/s single-threaded" and "inlet flow 450.0 mm3/s" out of the
# results: they have no 2+ space run before a number.
#
# The unit token is captured as-is and then normalised, because Rust's
# `{:>10.2?}` Duration formatting emits U+00B5 (MICRO SIGN) while other tools
# emit U+03BC (GREEK SMALL LETTER MU). Reducing to the leading ASCII letters
# means neither form has to be special-cased.
DUR = re.compile(r"^(\S.*?)\s{2,}([0-9]*\.?[0-9]+)\s*([^\s(]+)")


def unit_ns(token):
    """Normalise a duration unit token to nanoseconds, or None if unknown.

    Rust's `{:>10.2?}` Duration formatting emits U+00B5 (MICRO SIGN) for
    microseconds while some tools emit U+03BC (GREEK SMALL LETTER MU), so the
    micro prefix is matched as a character class rather than a literal.
    """
    t = token.strip()
    if not t:
        return None
    if t[0] in "µμ":  # micro sign / greek small letter mu
        return UNIT["us"] if t[1:] == "s" else None
    return UNIT.get(t)


current = {}
bench = None
for line in open(raw, encoding="utf-8", errors="replace"):
    stripped = line.strip()
    b = BENCH.match(stripped)
    if b:
        bench = b.group(1)
        continue
    m = DUR.match(stripped)
    if not m or not bench:
        continue
    scale = unit_ns(m.group(3))
    if scale is None:
        continue
    current[f"{bench}/{m.group(1)}"] = float(m.group(2)) * scale

if not current:
    sys.stderr.write("ERROR: no benchmark stages parsed from the output.\n"
                     "The benches are harness-free; if their output format changed,\n"
                     "update the parser in scripts/bench-baseline.sh.\n")
    sys.exit(2)

def load_baseline():
    base = {}
    if os.path.exists(baseline_path):
        for line in open(baseline_path):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            k, v = line.rsplit(None, 1)
            base[k] = float(v)
    return base

base = load_baseline()

if update:
    with open(baseline_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("# Benchmark baseline, in nanoseconds per stage.\n")
        f.write("# Generated by: scripts/bench-baseline.sh --update\n")
        f.write("# Compared by: scripts/bench-baseline.sh (CI, via benchmark.yml)\n")
        f.write("#\n")
        f.write("# Regenerate deliberately, on the same machine class, and read the diff:\n")
        f.write("# a baseline that drifts silently is worse than no baseline.\n")
        for k in sorted(current):
            f.write(f"{k} {current[k]:.0f}\n")
    print(f"Updated {baseline_path} with {len(current)} stage(s).")
    sys.exit(0)

if not base:
    sys.stderr.write("ERROR: no baseline found. Create one with --update.\n")
    sys.exit(2)

print()
print(f"| Stage | Baseline | Current | Drift | Within {threshold:g} % |")
print("|---|---:|---:|---:|:--:|")

regressions, added, unknown = [], [], []
for k in sorted(set(base) | set(current)):
    if k not in base:
        added.append(k)
        continue
    if k not in current:
        unknown.append(k)
        continue
    b, c = base[k], current[k]
    pct = ((c - b) / b * 100.0) if b else float("inf")
    ok = pct <= threshold
    print(f"| `{k}` | {b/1e6:.2f} ms | {c/1e6:.2f} ms | {pct:+.1f} % | {'yes' if ok else '**NO**'} |")
    if not ok:
        regressions.append((k, b, c, pct))

for k in added:
    print(f"NEW STAGE (no baseline): {k}")
for k in unknown:
    print(f"MISSING STAGE (in baseline, not run): {k}")

print()
if regressions:
    for k, b, c, pct in regressions:
        print(f"REGRESSION: {k} {b/1e6:.2f} ms -> {c/1e6:.2f} ms ({pct:+.1f} %)", file=sys.stderr)
    if unknown:
        print("A missing stage is treated as inconclusive, not as a pass.", file=sys.stderr)
    sys.exit(1)
if unknown:
    sys.exit(1)
print(f"No stage regressed beyond +{threshold:g} %.")
PYEOF